//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDCADataRecordImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalIntake
    {
        public System.Guid id { get; set; }
        public System.Guid facility_id { get; set; }
        public System.Guid user_id { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> RecordStatus { get; set; }
        public int RecordYear { get; set; }
        public int RecordMonth { get; set; }
        public Nullable<int> AdultC_StrayAtLarge { get; set; }
        public Nullable<int> UT5MC_StrayAtLarge { get; set; }
        public Nullable<int> AdultF_StrayAtLarge { get; set; }
        public Nullable<int> UT5MF_StrayAtLarge { get; set; }
        public Nullable<int> AdultC_RelinquishedByOwner { get; set; }
        public Nullable<int> UT5MC_RelinquishedByOwner { get; set; }
        public Nullable<int> AdultF_RelinquishedByOwner { get; set; }
        public Nullable<int> UT5MF_RelinquishedByOwner { get; set; }
        public Nullable<int> AdultC_OwnerRequestedEuthanasia { get; set; }
        public Nullable<int> UT5MC_OwnerRequestedEuthanasia { get; set; }
        public Nullable<int> AdultF_OwnerRequestedEuthanasia { get; set; }
        public Nullable<int> UT5MF_OwnerRequestedEuthanasia { get; set; }
        public Nullable<int> AdultC_TransferredFromAgency { get; set; }
        public Nullable<int> UT5MC_TransferredFromAgency { get; set; }
        public Nullable<int> Adultf_TransferredFromAgency { get; set; }
        public Nullable<int> UT5Mf_TransferredFromAgency { get; set; }
        public Nullable<int> AdultC_OtherIntakes { get; set; }
        public Nullable<int> UT5MC_OtherIntakes { get; set; }
        public Nullable<int> AdultF_OtherIntakes { get; set; }
        public Nullable<int> UT5MF_OtherIntakes { get; set; }
        public Nullable<int> AgeUnknownC_StrayAtLarge { get; set; }
        public Nullable<int> AgeUnknownF_StrayAtLarge { get; set; }
        public Nullable<int> AgeUnknownC_RelinquishedByOwner { get; set; }
        public Nullable<int> AgeUnknownF_RelinquishedByOwner { get; set; }
        public Nullable<int> AgeUnknownC_OwnerRequestedEuthenasia { get; set; }
        public Nullable<int> AgeUnknownF_OwnerRequestedEuthenasia { get; set; }
        public Nullable<int> AgeUnknownC_TransferredFromAgency { get; set; }
        public Nullable<int> AgeUnknownF_TransferredFromAgency { get; set; }
        public Nullable<int> AgeUnknownC_OtherIntakes { get; set; }
        public Nullable<int> AgeUnknownF_OtherIntakes { get; set; }
        public Nullable<int> C_ReturnToField { get; set; }
        public Nullable<int> F_ReturnToField { get; set; }
    
        public virtual Org_Facility Org_Facility { get; set; }
    }
}
