//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDCADataRecordImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Org_Facility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Org_Facility()
        {
            this.AnimalCounts = new HashSet<AnimalCount>();
            this.AnimalIntakes = new HashSet<AnimalIntake>();
            this.AnimalOutcomes = new HashSet<AnimalOutcome>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid Org_id { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string County { get; set; }
        public string Type { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<decimal> EstCommIntake { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> ReminderSentDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalCount> AnimalCounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalIntake> AnimalIntakes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalOutcome> AnimalOutcomes { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
