//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDCADataRecordImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organization()
        {
            this.Org_Facility = new HashSet<Org_Facility>();
        }
    
        public System.Guid id { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string County { get; set; }
        public string WebsiteURL { get; set; }
        public Nullable<int> Budget { get; set; }
        public Nullable<int> OrgEstAnnualIntake { get; set; }
        public string CommEstAnnualIntake { get; set; }
        public Nullable<int> AuthorizedPerson { get; set; }
        public Nullable<int> PrimaryContact { get; set; }
        public Nullable<int> SecondContact { get; set; }
        public string OtherContact { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Logo { get; set; }
        public string Type { get; set; }
        public string SDCA_Application { get; set; }
        public string FacilityDetail { get; set; }
        public Nullable<bool> AgreeCompleteDataMatrix { get; set; }
        public Nullable<bool> ShareData { get; set; }
        public string SACReview { get; set; }
        public string Notes { get; set; }
        public string ReferringOrg { get; set; }
        public string EIN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Org_Facility> Org_Facility { get; set; }
    }
}
